import json

with open('src/data/destinations.json') as f:
    dests = json.load(f)

new = [
    {"id": "d91", "name": "אנייקו", "nameEn": "Antigua Guatemala", "country": "גואטמלה", "countryEn": "Guatemala",
     "countryCode": "GT", "currencyCode": "GTQ", "region": "Americas", "lat": 14.56, "bestMonths": [11, 12, 1, 2, 3],
     "avgDailyBudgetUSD": 30, "minStars": [2, 3, 4], "hiddenGem": True,
     "description": "עיר קולוניאלית צבעונית מוקפת הרי געש, בירתה הקודמת של גואטמלה.",
     "descriptionEn": "A colorful colonial city ringed by volcanoes, Guatemala's former capital.",
     "theme": "historic", "tags": ["היסטוריה", "הרים"], "tagKeys": ["history", "mountains"]},
    {"id": "d92", "name": "לה פורטונה", "nameEn": "La Fortuna", "country": "קוסטה ריקה", "countryEn": "Costa Rica",
     "countryCode": "CR", "currencyCode": "CRC", "region": "Americas", "lat": 10.47, "bestMonths": [12, 1, 2, 3],
     "avgDailyBudgetUSD": 45, "minStars": [3, 4], "hiddenGem": True,
     "description": "כפר הרפתקאות למרגלות הר הגעש ארנל, עם מעיינות חמים טבעיים.",
     "descriptionEn": "An adventure village at the foot of Arenal Volcano, with natural hot springs.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d93", "name": "גרנדה", "nameEn": "Granada", "country": "ניקרגואה", "countryEn": "Nicaragua",
     "countryCode": "NI", "currencyCode": "NIO", "region": "Americas", "lat": 11.93, "bestMonths": [12, 1, 2, 3],
     "avgDailyBudgetUSD": 28, "minStars": [2, 3, 4], "hiddenGem": True,
     "description": "העיר הקולוניאלית העתיקה ביותר ביבשת, על שפת אגם קוקיבולקה.",
     "descriptionEn": "The oldest colonial city in the Americas, on the shore of Lake Cocibolca.",
     "theme": "historic", "tags": ["היסטוריה", "אגם"], "tagKeys": ["history", "lake"]},
    {"id": "d94", "name": "צ'יקו לגונה", "nameEn": "Chiloé Island", "country": "צ'ילה", "countryEn": "Chile",
     "countryCode": "CL", "currencyCode": "CLP", "region": "Americas", "lat": -42.62, "bestMonths": [12, 1, 2, 3],
     "avgDailyBudgetUSD": 42, "minStars": [2, 3], "hiddenGem": True,
     "description": "אי בתי עץ על כלונסאות וכנסיות עץ ייחודיות, מנותק מהיבשת בתרבותו.",
     "descriptionEn": "An island of stilt houses and unique wooden churches, culturally distinct from the mainland.",
     "theme": "island", "tags": ["טבע", "ייחודי"], "tagKeys": ["nature", "unique"]},
    {"id": "d95", "name": "וילה דה לבה", "nameEn": "Villa de Leyva", "country": "קולומביה", "countryEn": "Colombia",
     "countryCode": "CO", "currencyCode": "COP", "region": "Americas", "lat": 5.63, "bestMonths": [12, 1, 2, 7],
     "avgDailyBudgetUSD": 30, "minStars": [3, 4], "hiddenGem": True,
     "description": "עיירה קולוניאלית עם כיכר האבן הגדולה ביותר בדרום אמריקה.",
     "descriptionEn": "A colonial town with one of South America's largest stone squares.",
     "theme": "historic", "tags": ["היסטוריה", "כפרי"], "tagKeys": ["history", "village"]},
    {"id": "d96", "name": "בניוס", "nameEn": "Baños", "country": "אקוודור", "countryEn": "Ecuador",
     "countryCode": "EC", "currencyCode": "USD", "region": "Americas", "lat": -1.4, "bestMonths": [10, 11, 12, 1],
     "avgDailyBudgetUSD": 26, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיירת הרפתקאות בין מפלים והר געש פעיל, עם מעיינות מרפא.",
     "descriptionEn": "An adventure town amid waterfalls and an active volcano, with thermal spas.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d97", "name": "פוקון", "nameEn": "San Pedro de Atacama", "country": "צ'ילה", "countryEn": "Chile",
     "countryCode": "CL", "currencyCode": "CLP", "region": "Americas", "lat": -22.91, "bestMonths": [9, 10, 11, 3, 4],
     "avgDailyBudgetUSD": 40, "minStars": [2, 3, 4], "hiddenGem": True,
     "description": "כפר מדבר בגובה רב, שער למדבר אטקמה ולשמי הכוכבים הבהירים בעולם.",
     "descriptionEn": "A high-altitude desert village, gateway to the Atacama and some of the world's clearest night skies.",
     "theme": "desert", "tags": ["ייחודי", "טבע"], "tagKeys": ["unique", "nature"]},
    {"id": "d98", "name": "פאיה קלסטה", "nameEn": "Playa Venao", "country": "פנמה", "countryEn": "Panama",
     "countryCode": "PA", "currencyCode": "USD", "region": "Americas", "lat": 7.42, "bestMonths": [12, 1, 2, 3],
     "avgDailyBudgetUSD": 34, "minStars": [2, 3], "hiddenGem": True,
     "description": "מפרץ גלישה נסתר בחצי האי אזוארו, לפני שהתגלה על ידי ההמונים.",
     "descriptionEn": "A hidden surf bay on the Azuero Peninsula, before it's fully discovered by the crowds.",
     "theme": "coast", "tags": ["חופים", "גלישה"], "tagKeys": ["beaches", "surfing"]},
    {"id": "d99", "name": "וויסקאצ'רני", "nameEn": "Sucre", "country": "בוליביה", "countryEn": "Bolivia",
     "countryCode": "BO", "currencyCode": "BOB", "region": "Americas", "lat": -19.03, "bestMonths": [5, 6, 7, 8, 9],
     "avgDailyBudgetUSD": 24, "minStars": [2, 3, 4], "hiddenGem": True,
     "description": "הבירה החוקתית הלבנה של בוליביה, שקטה בהרבה מלה פאס.",
     "descriptionEn": "Bolivia's white constitutional capital, far quieter than La Paz.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d100", "name": "פונטה דל אסטה", "nameEn": "Punta del Diablo", "country": "אורוגוואי", "countryEn": "Uruguay",
     "countryCode": "UY", "currencyCode": "UYU", "region": "Americas", "lat": -34.06, "bestMonths": [12, 1, 2, 3],
     "avgDailyBudgetUSD": 32, "minStars": [2, 3], "hiddenGem": True,
     "description": "כפר דייגים על החוף האטלנטי, פחות מפותח מפונטה דל אסטה המוכרת.",
     "descriptionEn": "A fishing village on the Atlantic coast, less developed than famous Punta del Este.",
     "theme": "coast", "tags": ["חופים", "כפרי"], "tagKeys": ["beaches", "village"]},
    {"id": "d101", "name": "אורוואלד", "nameEn": "Uvita", "country": "קוסטה ריקה", "countryEn": "Costa Rica",
     "countryCode": "CR", "currencyCode": "CRC", "region": "Americas", "lat": 9.16, "bestMonths": [12, 1, 2, 3],
     "avgDailyBudgetUSD": 40, "minStars": [2, 3], "hiddenGem": True,
     "description": "חוף בצורת זנב לוויתן, שער לפארק הלאומי מרינו באיינה.",
     "descriptionEn": "A whale-tail-shaped beach, gateway to Marino Ballena National Park.",
     "theme": "coast", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d102", "name": "אוגדוגוגו", "nameEn": "Ouagadougou (Sindou)", "country": "בורקינה פאסו", "countryEn": "Burkina Faso",
     "countryCode": "BF", "currencyCode": "XOF", "region": "Africa", "lat": 10.67, "bestMonths": [11, 12, 1, 2],
     "avgDailyBudgetUSD": 20, "minStars": [1, 2], "hiddenGem": True,
     "description": "צוקי סינדו - נופי אבן דרמטיים כמעט ולא מוכרים לתיירים זרים.",
     "descriptionEn": "The Sindou Peaks - dramatic rock formations almost unknown to foreign travelers.",
     "theme": "desert", "tags": ["טבע", "ייחודי"], "tagKeys": ["nature", "unique"]},
    {"id": "d103", "name": "לאליבלה", "nameEn": "Lalibela", "country": "אתיופיה", "countryEn": "Ethiopia",
     "countryCode": "ET", "currencyCode": "ETB", "region": "Africa", "lat": 12.03, "bestMonths": [10, 11, 12, 1, 2],
     "avgDailyBudgetUSD": 24, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיר כנסיות חצובות בסלע מהמאה ה-12, אתר עלייה לרגל נוצרי עתיק.",
     "descriptionEn": "A city of 12th-century rock-hewn churches, an ancient Christian pilgrimage site.",
     "theme": "historic", "tags": ["היסטוריה", "ייחודי"], "tagKeys": ["history", "unique"]},
    {"id": "d104", "name": "בוואקו", "nameEn": "Bwindi (Buhoma)", "country": "אוגנדה", "countryEn": "Uganda",
     "countryCode": "UG", "currencyCode": "UGX", "region": "Africa", "lat": -1.05, "bestMonths": [6, 7, 8, 12, 1, 2],
     "avgDailyBudgetUSD": 55, "minStars": [2, 3], "hiddenGem": True,
     "description": "כפר קטן בשער יער בווינדי, בית הגורילות ההרריות.",
     "descriptionEn": "A small village at the gate of Bwindi forest, home to mountain gorillas.",
     "theme": "mountain", "tags": ["טבע", "הרים"], "tagKeys": ["nature", "mountains"]},
    {"id": "d105", "name": "סאו טומה", "nameEn": "São Tomé", "country": "סאו טומה ופרינסיפה", "countryEn": "São Tomé and Príncipe",
     "countryCode": "ST", "currencyCode": "STN", "region": "Africa", "lat": 0.34, "bestMonths": [6, 7, 8, 9],
     "avgDailyBudgetUSD": 45, "minStars": [2, 3], "hiddenGem": True,
     "description": "אי קקאו טרופי קטן במפרץ גינאה, כמעט לא מתויר.",
     "descriptionEn": "A small tropical cocoa island in the Gulf of Guinea, almost untouristed.",
     "theme": "island", "tags": ["טבע", "חופים"], "tagKeys": ["nature", "beaches"]},
    {"id": "d106", "name": "פמבה", "nameEn": "Pemba Island", "country": "טנזניה", "countryEn": "Tanzania",
     "countryCode": "TZ", "currencyCode": "TZS", "region": "Africa", "lat": -5.17, "bestMonths": [6, 7, 8, 9],
     "avgDailyBudgetUSD": 35, "minStars": [2, 3], "hiddenGem": True,
     "description": "האי הירוק השקט של ארכיפלג זנזיבר, ללא ההמונים.",
     "descriptionEn": "The quiet green island of the Zanzibar archipelago, without the crowds.",
     "theme": "island", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d107", "name": "טרויה", "nameEn": "Ölüdeniz", "country": "טורקיה", "countryEn": "Turkey",
     "countryCode": "TR", "currencyCode": "TRY", "region": "Europe", "lat": 36.55, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 40, "minStars": [3, 4], "hiddenGem": True,
     "description": "מפרץ תכול-טורקיז מתחת לצוקים, בירת הפאראגליידינג של טורקיה.",
     "descriptionEn": "A turquoise lagoon beneath cliffs, Turkey's paragliding capital.",
     "theme": "coast", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d108", "name": "אמאסיה", "nameEn": "Amasya", "country": "טורקיה", "countryEn": "Turkey",
     "countryCode": "TR", "currencyCode": "TRY", "region": "Europe", "lat": 40.65, "bestMonths": [4, 5, 9, 10],
     "avgDailyBudgetUSD": 28, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיר נהר עות'מאנית עם קברי מלכים חצובים בסלע מעל הבתים.",
     "descriptionEn": "An Ottoman river town with rock-cut royal tombs looming above the houses.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d109", "name": "בוסניה - מוסטר", "nameEn": "Mostar", "country": "בוסניה והרצגובינה", "countryEn": "Bosnia and Herzegovina",
     "countryCode": "BA", "currencyCode": "BAM", "region": "Europe", "lat": 43.34, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 32, "minStars": [3], "hiddenGem": True,
     "description": "עיר הגשר העתיק המפורסם, בין תרבויות מזרח ומערב.",
     "descriptionEn": "The city of the famous Old Bridge, bridging East and West.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d110", "name": "ברוב", "nameEn": "Berat", "country": "אלבניה", "countryEn": "Albania",
     "countryCode": "AL", "currencyCode": "ALL", "region": "Europe", "lat": 40.71, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 28, "minStars": [2, 3], "hiddenGem": True,
     "description": "'עיר אלף החלונות' - בתים עות'מאניים מדורגים מעל נהר אוסום.",
     "descriptionEn": "The 'City of a Thousand Windows' - tiered Ottoman houses above the Osum river.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d111", "name": "אוהריד", "nameEn": "Ohrid", "country": "צפון מקדוניה", "countryEn": "North Macedonia",
     "countryCode": "MK", "currencyCode": "MKD", "region": "Europe", "lat": 41.12, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 30, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיר אגם עתיקה עם כנסיות ביזנטיות, אחת האגמים העתיקים בעולם.",
     "descriptionEn": "An ancient lakeside town with Byzantine churches, on one of the oldest lakes on Earth.",
     "theme": "lake", "tags": ["אגם", "היסטוריה"], "tagKeys": ["lake", "history"]},
    {"id": "d112", "name": "קוטור", "nameEn": "Perast", "country": "מונטנגרו", "countryEn": "Montenegro",
     "countryCode": "ME", "currencyCode": "EUR", "region": "Europe", "lat": 42.49, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 45, "minStars": [3, 4], "hiddenGem": True,
     "description": "כפר ברוקי זעיר על מפרץ קוטור, עם שני איים זעירים מולו.",
     "descriptionEn": "A tiny baroque village on the Bay of Kotor, facing two miniature islands.",
     "theme": "coast", "tags": ["חופים", "היסטוריה"], "tagKeys": ["beaches", "history"]},
    {"id": "d113", "name": "פאטמוס", "nameEn": "Patmos", "country": "יוון", "countryEn": "Greece",
     "countryCode": "GR", "currencyCode": "EUR", "region": "Europe", "lat": 37.32, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 60, "minStars": [3, 4], "hiddenGem": True,
     "description": "אי דודקנזי רוחני ורגוע, בו נכתב לפי המסורת ספר ההתגלות.",
     "descriptionEn": "A spiritual, low-key Dodecanese island, traditionally where the Book of Revelation was written.",
     "theme": "island", "tags": ["חופים", "היסטוריה"], "tagKeys": ["beaches", "history"]},
    {"id": "d114", "name": "פורוול", "nameEn": "Pyrgos (Santorini village)", "country": "יוון", "countryEn": "Greece",
     "countryCode": "GR", "currencyCode": "EUR", "region": "Europe", "lat": 36.37, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 65, "minStars": [3, 4], "hiddenGem": True,
     "description": "הכפר הישן והגבוה ביותר בסנטוריני, בלי הקהל של אויה.",
     "descriptionEn": "Santorini's oldest and highest village, without Oia's crowds.",
     "theme": "village", "tags": ["כפרי", "היסטוריה"], "tagKeys": ["village", "history"]},
    {"id": "d115", "name": "אלבארסין", "nameEn": "Albarracín", "country": "ספרד", "countryEn": "Spain",
     "countryCode": "ES", "currencyCode": "EUR", "region": "Europe", "lat": 40.41, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 50, "minStars": [3], "hiddenGem": True,
     "description": "עיירת אבן ורודה מימי הביניים על צוק, אחת היפות בספרד ולא מוכרת.",
     "descriptionEn": "A pink-stone medieval clifftop town, one of Spain's prettiest and least known.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d116", "name": "האלה", "nameEn": "Hallstatt (Gosau)", "country": "אוסטריה", "countryEn": "Austria",
     "countryCode": "AT", "currencyCode": "EUR", "region": "Europe", "lat": 47.55, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 55, "minStars": [3, 4], "hiddenGem": True,
     "description": "כפר אלפיני שקט ליד אגם גוסאו, נוף הררי דרמטי בלי הצפיפות של האלשטט.",
     "descriptionEn": "A quiet alpine village near Lake Gosau, dramatic mountain views without Hallstatt's crowds.",
     "theme": "mountain", "tags": ["הרים", "אגם"], "tagKeys": ["mountains", "lake"]},
    {"id": "d117", "name": "טרייר", "nameEn": "Bacharach", "country": "גרמניה", "countryEn": "Germany",
     "countryCode": "DE", "currencyCode": "EUR", "region": "Europe", "lat": 50.06, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 55, "minStars": [3], "hiddenGem": True,
     "description": "כפר יין ימי-ביניימי על נהר הריין, מוקף חומה וכרמים.",
     "descriptionEn": "A medieval wine village on the Rhine, ringed by walls and vineyards.",
     "theme": "village", "tags": ["כפרי", "יין"], "tagKeys": ["village", "wine"]},
    {"id": "d118", "name": "פיילו טרם", "nameEn": "Piran", "country": "סלובניה", "countryEn": "Slovenia",
     "countryCode": "SI", "currencyCode": "EUR", "region": "Europe", "lat": 45.53, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 45, "minStars": [3], "hiddenGem": True,
     "description": "עיר נמל ונציאנית זעירה על חצי אי, כמעט ולא מוכרת מחוץ לסלובניה.",
     "descriptionEn": "A tiny Venetian port town on a peninsula, barely known outside Slovenia.",
     "theme": "coast", "tags": ["חופים", "היסטוריה"], "tagKeys": ["beaches", "history"]},
    {"id": "d119", "name": "לוארב", "nameEn": "Lauterbrunnen", "country": "שוויץ", "countryEn": "Switzerland",
     "countryCode": "CH", "currencyCode": "CHF", "region": "Europe", "lat": 46.59, "bestMonths": [6, 7, 8, 9],
     "avgDailyBudgetUSD": 85, "minStars": [3, 4], "hiddenGem": True,
     "description": "עמק עם 72 מפלים, שער לג'ונגפראו והאלפים הברניים.",
     "descriptionEn": "A valley of 72 waterfalls, gateway to the Jungfrau and Bernese Alps.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d120", "name": "וילנוב", "nameEn": "Annecy (Talloires)", "country": "צרפת", "countryEn": "France",
     "countryCode": "FR", "currencyCode": "EUR", "region": "Europe", "lat": 45.83, "bestMonths": [6, 7, 9],
     "avgDailyBudgetUSD": 60, "minStars": [3, 4], "hiddenGem": True,
     "description": "כפר קטן על אגם אנסי, שקט יותר מעיר אנסי עצמה.",
     "descriptionEn": "A small village on Lake Annecy, quieter than the town of Annecy itself.",
     "theme": "lake", "tags": ["אגם", "טבע"], "tagKeys": ["lake", "nature"]},
]

dests.extend(new)
with open('src/data/destinations.json', 'w') as f:
    json.dump(dests, f, ensure_ascii=False, indent=2)

hidden = sum(1 for x in dests if x['hiddenGem'])
anchor = len(dests) - hidden
print(f"Added {len(new)}. Total: {len(dests)}. Hidden: {hidden}, Anchor: {anchor}, ratio 1:{hidden/anchor:.2f}")
