import json

with open('src/data/destinations.json') as f:
    dests = json.load(f)

new = [
    {"id": "d71", "name": "פוקוט", "nameEn": "Phu Quoc (Ham Ninh)", "country": "וייטנאם", "countryEn": "Vietnam",
     "countryCode": "VN", "currencyCode": "VND", "region": "Asia", "lat": 10.22, "bestMonths": [11, 12, 1, 2, 3],
     "avgDailyBudgetUSD": 28, "minStars": [3, 4], "hiddenGem": True,
     "description": "כפר דייגים שקט על אי פוקוק, לפני הפיתוח ההמוני בחלקים אחרים של האי.",
     "descriptionEn": "A quiet fishing village on Phu Quoc island, ahead of the island's mass development elsewhere.",
     "theme": "island", "tags": ["חופים", "כפרי"], "tagKeys": ["beaches", "village"]},
    {"id": "d72", "name": "פנום פנח - הרובע הצרפתי", "nameEn": "Kampot", "country": "קמבודיה", "countryEn": "Cambodia",
     "countryCode": "KH", "currencyCode": "KHR", "region": "Asia", "lat": 10.61, "bestMonths": [11, 12, 1, 2],
     "avgDailyBudgetUSD": 22, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיירת נהר קולוניאלית רגועה, ידועה בפלפל הירוק המקומי ובשקיעות.",
     "descriptionEn": "A laid-back colonial river town, known for its local pepper and sunsets.",
     "theme": "village", "tags": ["כפרי", "טבע"], "tagKeys": ["village", "nature"]},
    {"id": "d73", "name": "וואנג וייאנג", "nameEn": "Vang Vieng", "country": "לאוס", "countryEn": "Laos",
     "countryCode": "LA", "currencyCode": "LAK", "region": "Asia", "lat": 18.92, "bestMonths": [11, 12, 1, 2],
     "avgDailyBudgetUSD": 20, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיירת הרים על נהר, מוקפת מגדלי קארסט דרמטיים.",
     "descriptionEn": "A riverside mountain town ringed by dramatic karst towers.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d74", "name": "באנדיפור", "nameEn": "Bandipur", "country": "נפאל", "countryEn": "Nepal",
     "countryCode": "NP", "currencyCode": "NPR", "region": "Asia", "lat": 27.93, "bestMonths": [10, 11, 3, 4],
     "avgDailyBudgetUSD": 18, "minStars": [2, 3], "hiddenGem": True,
     "description": "כפר ניואר משומר על רכס הר, ללא כבישים לרכבים במרכז.",
     "descriptionEn": "A preserved Newar hilltop village, car-free at its center.",
     "theme": "village", "tags": ["כפרי", "הרים"], "tagKeys": ["village", "mountains"]},
    {"id": "d75", "name": "דיאני ביץ'", "nameEn": "Diani Beach", "country": "קניה", "countryEn": "Kenya",
     "countryCode": "KE", "currencyCode": "KES", "region": "Africa", "lat": -4.28, "bestMonths": [1, 2, 7, 8, 9],
     "avgDailyBudgetUSD": 32, "minStars": [3, 4], "hiddenGem": True,
     "description": "חוף חול לבן דרומית למומבסה, שקט יותר מהאתרים המוכרים.",
     "descriptionEn": "A white-sand beach south of Mombasa, quieter than the well-known resorts.",
     "theme": "coast", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d76", "name": "איטו", "nameEn": "Iringa", "country": "טנזניה", "countryEn": "Tanzania",
     "countryCode": "TZ", "currencyCode": "TZS", "region": "Africa", "lat": -7.77, "bestMonths": [6, 7, 8, 9],
     "avgDailyBudgetUSD": 24, "minStars": [2, 3], "hiddenGem": True,
     "description": "עיר גבעות קולוניאלית שקטה, שער לפארק הלאומי רוהאה.",
     "descriptionEn": "A quiet colonial hill town, gateway to Ruaha National Park.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d77", "name": "דהב", "nameEn": "Dahab", "country": "מצרים", "countryEn": "Egypt",
     "countryCode": "EG", "currencyCode": "EGP", "region": "Africa", "lat": 28.5, "bestMonths": [3, 4, 5, 10, 11],
     "avgDailyBudgetUSD": 26, "minStars": [2, 3, 4], "hiddenGem": True,
     "description": "כפר צלילה רגוע על חופי סיני, פחות מפותח משארם א-שייח'.",
     "descriptionEn": "A relaxed diving village on the Sinai coast, less developed than Sharm el-Sheikh.",
     "theme": "coast", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d78", "name": "אזילאל", "nameEn": "Azilal (Ouzoud)", "country": "מרוקו", "countryEn": "Morocco",
     "countryCode": "MA", "currencyCode": "MAD", "region": "Africa", "lat": 32.0, "bestMonths": [4, 5, 9, 10],
     "avgDailyBudgetUSD": 25, "minStars": [2, 3], "hiddenGem": True,
     "description": "כפר הרים ליד מפלי אוזוד, בין הגדולים והציוריים במרוקו.",
     "descriptionEn": "A mountain village near the Ouzoud Falls, among Morocco's largest and most scenic.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d79", "name": "הרי", "nameEn": "Hampi (Anegundi)", "country": "הודו", "countryEn": "India",
     "countryCode": "IN", "currencyCode": "INR", "region": "Asia", "lat": 15.34, "bestMonths": [11, 12, 1, 2],
     "avgDailyBudgetUSD": 16, "minStars": [2, 3], "hiddenGem": True,
     "description": "כפר עתיק מעבר לנהר מהמפי, שקט אפילו יותר מהאתר הראשי.",
     "descriptionEn": "An ancient village across the river from Hampi, even quieter than the main site.",
     "theme": "historic", "tags": ["היסטוריה", "כפרי"], "tagKeys": ["history", "village"]},
    {"id": "d80", "name": "וארקאלה", "nameEn": "Varkala", "country": "הודו", "countryEn": "India",
     "countryCode": "IN", "currencyCode": "INR", "region": "Asia", "lat": 8.73, "bestMonths": [11, 12, 1, 2],
     "avgDailyBudgetUSD": 20, "minStars": [2, 3, 4], "hiddenGem": True,
     "description": "צוקי חוף דרמטיים בקרלה, רגועים יותר מגואה.",
     "descriptionEn": "Dramatic clifftop beaches in Kerala, calmer than Goa.",
     "theme": "coast", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d81", "name": "אל ניידו", "nameEn": "El Nido", "country": "פיליפינים", "countryEn": "Philippines",
     "countryCode": "PH", "currencyCode": "PHP", "region": "Asia", "lat": 11.18, "bestMonths": [1, 2, 3, 4],
     "avgDailyBudgetUSD": 30, "minStars": [3, 4], "hiddenGem": True,
     "description": "לגונות טורקיז ומצוקי גיר בפלאוואן הצפונית.",
     "descriptionEn": "Turquoise lagoons and limestone cliffs in northern Palawan.",
     "theme": "island", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d82", "name": "סיקוינרס - לזי איילנד", "nameEn": "Malapascua", "country": "פיליפינים", "countryEn": "Philippines",
     "countryCode": "PH", "currencyCode": "PHP", "region": "Asia", "lat": 11.33, "bestMonths": [1, 2, 3, 4],
     "avgDailyBudgetUSD": 24, "minStars": [2, 3], "hiddenGem": True,
     "description": "אי צלילה קטן ידוע לצפייה בכרישי טרשר, כמעט ולא מתויר.",
     "descriptionEn": "A small diving island known for thresher shark sightings, barely touristed.",
     "theme": "island", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
    {"id": "d83", "name": "רילה", "nameEn": "Rila", "country": "בולגריה", "countryEn": "Bulgaria",
     "countryCode": "BG", "currencyCode": "BGN", "region": "Europe", "lat": 42.13, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 30, "minStars": [3], "hiddenGem": True,
     "description": "כפר הרים ליד מנזר רילה המפורסם, בלב הרי רילה.",
     "descriptionEn": "A mountain village near the famous Rila Monastery, deep in the Rila mountains.",
     "theme": "mountain", "tags": ["הרים", "היסטוריה"], "tagKeys": ["mountains", "history"]},
    {"id": "d84", "name": "וֶלִיקוֹ טרנובו", "nameEn": "Veliko Tarnovo", "country": "בולגריה", "countryEn": "Bulgaria",
     "countryCode": "BG", "currencyCode": "BGN", "region": "Europe", "lat": 43.08, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 32, "minStars": [3, 4], "hiddenGem": True,
     "description": "בירתה העתיקה של בולגריה, בנויה על גדות נהר מפותל.",
     "descriptionEn": "Bulgaria's medieval capital, built along a winding river gorge.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d85", "name": "סיביו", "nameEn": "Sibiu", "country": "רומניה", "countryEn": "Romania",
     "countryCode": "RO", "currencyCode": "RON", "region": "Europe", "lat": 45.79, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 34, "minStars": [3, 4], "hiddenGem": True,
     "description": "עיר סקסונית טרנסילבנית עם כיכר מדהימה ו'עיניים' על הגגות.",
     "descriptionEn": "A Transylvanian Saxon town with a stunning square and rooftop 'eyes'.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d86", "name": "לוקה", "nameEn": "Lucca", "country": "איטליה", "countryEn": "Italy",
     "countryCode": "IT", "currencyCode": "EUR", "region": "Europe", "lat": 43.84, "bestMonths": [4, 5, 9, 10],
     "avgDailyBudgetUSD": 60, "minStars": [3, 4], "hiddenGem": True,
     "description": "עיר טוסקנית מוקפת חומה שלמה שאפשר לרכוב עליה באופניים.",
     "descriptionEn": "A Tuscan town encircled by a complete, bike-able Renaissance wall.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d87", "name": "מונסנטו", "nameEn": "Monsanto", "country": "פורטוגל", "countryEn": "Portugal",
     "countryCode": "PT", "currencyCode": "EUR", "region": "Europe", "lat": 40.04, "bestMonths": [4, 5, 9, 10],
     "avgDailyBudgetUSD": 55, "minStars": [2, 3], "hiddenGem": True,
     "description": "כפר בנוי בין סלעי ענק, כונה 'הכפר הפורטוגלי ביותר'.",
     "descriptionEn": "A village built among giant boulders, once voted 'most Portuguese village'.",
     "theme": "village", "tags": ["כפרי", "ייחודי"], "tagKeys": ["village", "unique"]},
    {"id": "d88", "name": "זאגורוחוריה", "nameEn": "Zagorochoria", "country": "יוון", "countryEn": "Greece",
     "countryCode": "GR", "currencyCode": "EUR", "region": "Europe", "lat": 39.93, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 58, "minStars": [3, 4], "hiddenGem": True,
     "description": "אשכול כפרי אבן באפירוס, ליד קניון הוויקוס העמוק בעולם.",
     "descriptionEn": "A cluster of stone villages in Epirus, beside one of the world's deepest gorges.",
     "theme": "mountain", "tags": ["הרים", "טבע"], "tagKeys": ["mountains", "nature"]},
    {"id": "d89", "name": "צ'סקה שוֶמְיוֹבָה", "nameEn": "Kutná Hora", "country": "צ'כיה", "countryEn": "Czechia",
     "countryCode": "CZ", "currencyCode": "CZK", "region": "Europe", "lat": 49.95, "bestMonths": [5, 6, 9, 10],
     "avgDailyBudgetUSD": 45, "minStars": [3], "hiddenGem": True,
     "description": "עיירת כסף ימי-ביניימית עם כנסיית עצמות מפורסמת, שעה מפראג.",
     "descriptionEn": "A medieval silver-mining town with a famous bone church, an hour from Prague.",
     "theme": "historic", "tags": ["היסטוריה", "אדריכלות"], "tagKeys": ["history", "architecture"]},
    {"id": "d90", "name": "קמפנרו", "nameEn": "Comporta", "country": "פורטוגל", "countryEn": "Portugal",
     "countryCode": "PT", "currencyCode": "EUR", "region": "Europe", "lat": 38.38, "bestMonths": [5, 6, 9],
     "avgDailyBudgetUSD": 65, "minStars": [3, 4], "hiddenGem": True,
     "description": "כפרי חוף אמינליים בין שדות אורז, בלי ההמונים של אלגרווה.",
     "descriptionEn": "Minimalist beach villages amid rice paddies, without the Algarve crowds.",
     "theme": "coast", "tags": ["חופים", "טבע"], "tagKeys": ["beaches", "nature"]},
]

dests.extend(new)
with open('src/data/destinations.json', 'w') as f:
    json.dump(dests, f, ensure_ascii=False, indent=2)

hidden = sum(1 for x in dests if x['hiddenGem'])
anchor = len(dests) - hidden
print(f"Added {len(new)}. Total now: {len(dests)}. Hidden: {hidden}, Anchor: {anchor}, ratio 1:{hidden/anchor:.1f}")
